# Generated by Django 5.1.1 on 2024-10-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRCConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(db_index=True, max_length=255, unique=True)),
                ('port', models.IntegerField()),
                ('ssl', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_sasl', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IRCChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='irc_xdcc_manager.ircconnection')),
            ],
        ),
        migrations.CreateModel(
            name='XDCCOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot', models.CharField(max_length=255)),
                ('pack_number', models.IntegerField()),
                ('pack_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irc_xdcc_manager.ircchannel')),
            ],
        ),
    ]
